version: '3.7'

volumes:
  pgdata:
  grafana-lib:
  grafana-log:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    environment:
      TIMESCALEDB_TELEMETRY: 'off'
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:7.1.0-beta1
    depends_on:
      - timescaledb
    user: '1000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_ROOT_URL: ${GRAFANA_URL}
      GF_USERS_VIEWERS_CAN_EDIT: 'true'
      GF_INSTALL_PLUGINS: 'flant-statusmap-panel'
      GF_USERS_DEFAULT_THEME: light
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: '/etc/grafana/provisioning/dashboards/home.json'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: host.docker.internal:5433
    ports:
      - '3001:3000'
    volumes:
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - ./grafana/:/etc/grafana/provisioning/
