{
 "title": "Passive Completion",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n## Passive RMT Record Count\n\nThis is the passive rmt app battery and location record count.\n",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Phone Battery Level Record Count",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h, 0),\n  \"userId\" AS metric,\n  count(\"batteryLevel\") AS \"\"\"batteryLevel\"\"\"\nFROM android_phone_battery_level\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Phone Relative Location Record Count",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h, 0),\n  \"userId\" AS metric,\n  count(\"latitude\") AS \"\"\"latitude\"\"\"\nFROM android_phone_relative_location\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "content": "\n## Fitbit Wear Time\n\nThis is the Fitbit wear time based on intraday heart rate (steps for now). This is based on the percentage of data available per hour.\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Fitbit Wear Time Percentage",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h, 0),\n  \"userId\" AS metric,\n  (count(\"steps\")*100)/60 AS \"\"\"steps_record_count\"\"\"\nFROM connect_fitbit_intraday_steps\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Fitbit Step Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h, 0),\n  \"userId\" AS metric,\n  sum(\"steps\") AS \"\"\"steps\"\"\"\nFROM connect_fitbit_intraday_steps\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}